version: "3.2"

volumes:
  ? geoserver-data

services:
  geoserver:
    container_name: geoserver
    image: kartoza/geoserver:2.13.0
    volumes:
      - geoserver-data:/opt/geoserver/data_dir
      - type: bind
        source: ./processing/images/output
        target: /images_output
    ports:
      - "8600:8080"
    restart: on-failure
    env_file:
      - docker-env/geoserver.env
    healthcheck:
      test: curl --fail -s http://localhost:8080/ || exit 1
      interval: 1m30s
      timeout: 10s
      retries: 3
  webserver:
    container_name: webapp
    image: nginx
    volumes:
      - type: bind
        source: ./webapp
        target: /usr/share/nginx/html
    ports:
      - "8000:80"
